name: a2b
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.0.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dots_indicator: ^2.1.0
  dotted_border: ^2.0.0+3
  emoji_picker_flutter: ^1.5.4
  equatable: ^2.0.3
  file_picker: ^5.2.11
  firebase_auth: ^4.4.2
  firebase_auth_web: ^5.3.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.2.0
  firebase_storage: ^11.0.1
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.1.1
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.5
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.0.8
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.5
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0
  gradient_borders: ^1.0.0
  html: ^0.15.3
  http: ^0.13.5
  iconsax: ^0.0.8
  image_cropper: ^3.0.3
  image_picker: ^0.8.4+9
  intl: any
  intl_phone_field: ^3.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

  l10n_flutter: ^1.0.0
  location: ^4.4.0
  lottie: ^2.3.2
  mobx: ^2.1.4
  nb_utils: ^5.0.8
  onesignal_flutter: ^3.5.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.0.13
  swipe_to: ^1.0.2
  syncfusion_flutter_calendar: ^21.1.41
  table_calendar: ^3.0.8
  timeago: ^3.3.0
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#121212"
  image: assets/images/1x/Artboard14.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf

  assets:
    - assets/images/1x/
    - assets/images/icons/
    - assets/json/
    - assets/images/1x/demo.jpg
