name: a2b
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #google_maps_flutter: ^2.1.9
  flutter_svg: ^1.1.6
  flutter_statusbarcolor_ns: ^0.5.0
  path_provider: ^2.0.11
  flutter_login: ^4.1.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  google_sign_in: ^6.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+9
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  country_code_picker: ^3.0.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  google_sign_in_web: ^0.12.0
  flutter_riverpod: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf

  assets:
    - assets/images/1x/
    - assets/images/icons/

